services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/user/src/app:ro
    command: ["uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=aQbvvgL1ekDasXJ0Ntwg
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - DATABASE_URL=postgresql://postgres:aQbvvgL1ekDasXJ0Ntwg@postgres:5432/fastapi
      - SECRET_KEY=09d25e094faa2556c818166b7a99f6f0f4c3b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=180

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=aQbvvgL1ekDasXJ0Ntwg
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"  # Expose PostgreSQL port to the host
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: